@echo off
echo Starting Phorencial CRM Development Server...
echo.
echo Limpiando cache...
rmdir /s /q .next 2>nul
echo.
echo Verificando TypeScript...
npx tsc --noEmit
echo.
echo Iniciando Next.js...
npm run dev
pause
